In [2]:
# Day 3 - NumPy Basics

In [3]:
import numpy as np
print("NumPy imported successfully!")

NumPy imported successfully!


In [4]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)
print(type(arr1))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [5]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [6]:
arr = np.array([5, 10, 15, 20])
print("Addition:", arr + 5)
print("Subtraction:", arr - 2)
print("Multiplication:", arr * 2)
print("Division:", arr / 5)

Addition: [10 15 20 25]
Subtraction: [ 3  8 13 18]
Multiplication: [10 20 30 40]
Division: [1. 2. 3. 4.]


In [7]:
numbers = np.array([10, 20, 30, 40, 50])
print("Sum:", np.sum(numbers))
print("Average:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

Sum: 150
Average: 30.0
Maximum: 50
Minimum: 10


In [8]:
arr = np.array([100, 200, 300, 400, 500])
print(arr[0])
print(arr[2])
print(arr[-1])

100
300
500


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Multiplication:", a * b)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [11]:
marks = np.array([85, 90, 78, 88, 95])
print("Marks:", marks)
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

Marks: [85 90 78 88 95]
Average: 87.2
Highest: 95
Lowest: 78
